file(SHA256 "${INPUT}" digest)
if(NOT DEFINED NAME)
  get_filename_component(NAME "${INPUT}" NAME)
endif()
if(NOT DEFINED OUTPUT)
  get_filename_component(dir "${INPUT}" DIRECTORY)
  set(OUTPUT "${dir}/SHA256SUMS.txt")
endif()
file(WRITE "${OUTPUT}" "${digest}  ${NAME}\n")
